### ISSUE TITLE
TheQube 0.92 still not authorising access token

### ISSUE THREAD

**Issue by RunningLeopard2** [Oire/TheQube#74] opened 2018-07-10 16:22 UTC
Greetings all.

TheQube 0.92 on 64 byt windows systems still doesn't bring up an access token from twitter. I uninstalled the previous version before reinstalling this new one and it still gives the same issue.
I wonder if this is a twitter problem instead of a client one?

**Comment by manuelcortez** [comment] 2018-07-10 16:29
I am not following this repo so much but, maybe it's caused by [this change](https://blog.twitter.com/developer/en_us/topics/tools/2018/Sign-in-with-Twitter-users-must-whitelist-callback-URLs.html) in Twitter's Callback URL authorization process?

**Comment by Menelion** [comment] 2018-07-10 19:07
Thanks Manuel! Yepp, that was it. @RunningLeopard2, please confirm it is fixed now.

**Comment by RunningLeopard2** [comment] 2018-07-18 17:41
Greetings all. This authorisation issue has been resolved.

**Closed** 2018-07-18 17:40 UTC
